type userInfo = {
  loginId: string;
  name: string;
  email: string;
  hp: string;
  hpIs: string;
  hpTb: string;
  birthday: string;
  gender: string;
  nickName: string;
  gpkiYn: string;
  memDiv: string;
  dormantYn: 'Y' | 'N';
  dormantYear: string;
  scCode: number;
  scName: string;
  scAddr: null;
  scTel: null;
  loginDt: string;
  pwModDt: string;
  regDt: string;
  scInfo: {
    scIdx: number;
    closeYn: 'Y' | 'N';
    deployYn: 'Y' | 'N';
    eduIdx: number;
    eduName: string;
    localArea: string;
    schoolType: string;
    cityType: string;
    council: string;
    schoolName: string;
    schoolSub: string;
    master: string;
    post1: string;
    post2: string;
    address1: string;
    address2: string;
    doroZipCode: string;
    doroAddr: string;
    tel1: string;
    tel2: string;
    tel3: string;
    fax1: string;
    fax2: string;
    fax3: string;
    classNo: number;
    serviceMemo: null;
    schoolKind: number;
    domain: null;
    scDivCode: string;
    eduCode: null;
    eYear: string;
    eType: string;
    SIDO: string;
    GUGUN: string;
  };
  mId: string;
};
